name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CAMINHO_PROJETO_TESTES: ./APITemperatura.Testes/APITemperatura.Testes.csproj
      CAMINHO_PROJETO_WEBAPP: ./APITemperatura
      DOCKER_CONTAINER_REGISTRY: groffegithubactions.azurecr.io
      NOME_IMAGEM: $DOCKER_CONTAINER_REGISTRY/apitemperaturas

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15

    - name: Executar testes automatizados
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal

    - name: Login no Container Registry
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ secrets.DOCKER_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
        registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
        
    - name: Build e Push no Azure Container Registry
      run: |
        cd ${{ env.CAMINHO_PROJETO_WEBAPP }}
        docker build . --file Dockerfile --tag ${{ env.NOME_IMAGEM }}:latest
        docker tag ${{ env.NOME_IMAGEM }}:latest ${{ env.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.NOME_IMAGEM }}
